export const postingDetailStyles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'center',
    minHeight: '100vh',
    width: '100%',
    padding: '0 !important',
    margin: '0 !important',
    backgroundColor: '#f0f0f0',
    boxSizing: 'border-box',
  },
  posting: {
    px: 4,
    pt: 3,
    width: {
      xs: '100%',
      md: '50%',
    },
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fafafa',
    boxSizing: 'border-box',
  },
  postingHeader: {
    width: '100%',
    position: 'sticky',
    opacity: '0.9',
    top: 0,
    bgcolor: 'white',
    zIndex: 1000,
    borderBottom: '1px solid #eee',
    py: 2,
    px: 3,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    boxSizing: 'border-box',
  },
  likeCount: {
    position: 'absolute',
    bottom: -10,
    left: '50%',
    transform: 'translateX(-50%)',
    fontSize: '0.75rem',
    color: 'text.secondary',
  },
  userInfoBox: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    p: 1,
    mb: 3,
    width: '100%',
    borderBottom: '1px solid #eee',
  },
  bookPreviewBox: {
    width: '50%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    mt: '1rem',
    padding: '0',
  },
  bookCard: {
    width: '100%',
    display: 'flex !important',
    flexDirection: 'row !important',
    backgroundColor: 'transparent',
    padding: '1rem',
    height: '100px',
    '& .MuiCardMedia-root': {
      width: '80px',
      height: '100%',
      padding: 'auto',
      borderRadius: '0',
    },
    '& .MuiCardContent-root': {
      flex: 1,
      padding: '0.1rem',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      boxSizing: 'border-box',
    },
    '& .MuiTypography-body1': {
      fontSize: '14px',
    },
    '& .MuiTypography-body2': {
      fontSize: '11px',
    },
  },
  otherPostingBox: {
    width: '100%',
    my: 5,
    px: 4,
    boxSizing: 'border-box',
  },
  otherPostingTitle: {
    mb: 2,
    fontWeight: 'bold',
  },
};
